apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eve
  name: vehicle-api
  labels:
        app: vehicle-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vehicle-api
  template:
    metadata:
      labels:
        app: vehicle-api
    spec:
      automountServiceAccountToken: false
      containers:
        - name: vehicle-api
          image: "app-image"
          resources:
            limits:
              cpu: "0.25"
              memory: "256Mi"
          env:
            - name: PORT
              value: "3000"
            - name: GIN_MODE
              value: "release"
          ports:
          - name: http-port
            containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: http-port
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: http-port
            failureThreshold: 30
            periodSeconds: 5
