apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eve
  name: vehicle-api
  labels:
        app: vehicle-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-api
  template:
    metadata:
      labels:
        app: vehicle-api
    spec:
      automountServiceAccountToken: false
      containers:
        - name: vehicle-api
          image: "app-image"
          resources:
            limits:
              cpu: "0.25"
              memory: "256Mi"
          env:
            - name: PORT
              value: "3000"
          ports:
          - containerPort: 3000
